docs/installation/systemd.md
The systemd doc still used streamdeck_ui instead of streamdeck-linux-gui. 
Also fixed the pyenv part but I am wondering if this shouldn't be moved to it's own dedicated file.
=> Fix systemd doc referencing old project

README.md, pyproject.toml, streamdeck_ui/cli/commands.py, streamdeck_ui/cli/server.py, streamdeck_ui/gui.py, tests/cli/test_commands.py
Hi, thank you for keeping the project alive!
I am submitting a Pull Request to add a new feature to your project. This feature allows for controlling a StreamDeck through the terminal.
This PR provides the following functions:
- transition pages
- change button brightness
- change button text
- change button text alignment
- changing the command associated with a button
- change text input associated with button
- change key input associated with button
- change button icon
- clear button icon
These functions can be used by running the command streamdeckc with specific arguments. For example, the command streamdeckc --page 1 will navigate to the second page of the StreamDeck-UI.
To send commands to the StreamDeck-UI, the feature uses a Unix domain socket located at …
=> Operating StreamDeck from a terminal

streamdeck_ui/cli/server.py
The `command` value parsed by https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/pull/37/files#diff-3dcd8b64032078f57e32f8e99030f0ff1fb419f3dbdbad5cc8429196029a4977R133 is different to what the CLI sends and therefore never generates and executes the according Class-instance. The `set_alignment` function didn't need that change and therefore is currently the only one working. With this change all other commands work as expected.
CC @asuka1975
=> Fix CLI commands

streamdeck_ui/display/text_filter.py, streamdeck_ui/gui.py, streamdeck_ui/main.ui, streamdeck_ui/ui_main.py
Adds support for multiline button labels
* Uses QTextEdit in place of QLineEdit
* Add multiline support when calculating horizontal and vertical alignments
* Move horizontal and vertical alignment buttons to vertical layout to mesh better next to larger text widget
=> feat: Add support for multiline button labels

streamdeck_ui/gui.py
Include support for numpad keys, fixes #49 
- prefix number with "numpad_", ej: `numpad_0`, `numpad_9`
- also supports `enter`, `substract`, `add`, `divide`, `multiply`, `decimal`, `equal`
=> Add support for numpad keys

pyproject.toml, scripts/lint.sh, streamdeck_ui/api.py, streamdeck_ui/cli/server.py, streamdeck_ui/dimmer.py, streamdeck_ui/display/background_color_filter.py, streamdeck_ui/display/display_grid.py, streamdeck_ui/display/empty_filter.py, streamdeck_ui/display/filter.py, streamdeck_ui/display/image_filter.py, streamdeck_ui/display/keypress_filter.py, streamdeck_ui/display/pulse_filter.py, streamdeck_ui/display/text_filter.py, streamdeck_ui/gui.py
The project uses [black](https://pypi.org/project/black/) and [isort](https://pypi.org/project/isort/) to ensure the correct format of the files but if you look at the pyproject.toml you'll notice that black was configure there with 100 line length but the scripts/lint.sh which is used in the pipeline the line lenght is set to 200 making really hard to use autoformat tools in the IDE/text editor
I consider 100 very little and 200 a lot, I set in this PR the line length consistently to 120
- Make consistent the line length in pyproject.toml and scripts/lint.sh to 120 characters
- Format source files using `./scripts/lint.sh`
- I checked [isort documentation](https://pycqa.github.io/isort/docs/configuration/config_files.html#isortcfg-preferred-format)  and it looks like the pyproject.toml …
=> Make project lint consistent and update to 120 characters per line

scripts/lint.sh, streamdeck_ui/api.py, streamdeck_ui/config.py, streamdeck_ui/display/text_filter.py, streamdeck_ui/fonts.py, streamdeck_ui/gui.py, streamdeck_ui/main.ui, streamdeck_ui/ui_main.py, tests/test_fonts.py
This pull request adds support for system fonts. 
- Currently hardcoded to only list fonts that support RFC-3066 language = "en". We may want to change this behavior?
- Continues to include Roboto fonts as a fallback if no system fonts are found. If Roboto doesn't exist in the system fonts list it will be added.
- Adds a font_style selection in the GUI which may make things more cluttered... would consider a different layout.
- We do not use QFontComboBox or QFont (directly) because it does not support retrieving the font file path which is required for using with pillow. 
- Added vuln 59726 to ignore list to get it to pass the linter... the vuln is part of the "hypothesis" package so would affect testing only, though I don't believe hypothesis is currently used...
=> feat: Add support for system fonts

streamdeck_ui/modules/utils/timers.py
debounce was not disconnecting correctly previous calls ending by call previous partial_func when timeout.
this results in bad behavior when you type in any debouced field
=> fix(timers.py): ensure to disconnect previous debouced calls

streamdeck_ui/api.py, streamdeck_ui/config.py, streamdeck_ui/logger.py, tests/api/conftest.py, tests/api/test_default_state.py, tests/common.py
Hello, :wave: 
This is a proposal for the problem discussed here:  https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/35.
Which raise multiple different but linked issue:  initial configuration, cloning configuration, sharing configuration.
This proposal give only a "default" configuration.
The idea is able to have some kind of default configuration for any new connected streamdeck.
At first connection, it gets a default configuration. If you save the configuration, the specific streamdeck will have a configuration for itself.
The current implementation is only usable by modifying manually the configuration file, but is still a great workaround for many usages. We can expect a support Gui with buttons like:
- "set as default config" 
-  "set as default Stream Deck …
=> feat: Add support for default config

streamdeck_ui/display/image_filter.py
if P mode is detected converted try to convert to RGBA. GIF are not transparent by nature, but there's a modern technique that allow to encode transparency in a palette in the first frame. the application was not recognising that frame as RGBA resulting in a glitch (white flash)
Fix the #21
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/d7a39ca6-1bd8-488a-9139-b5a17f3d5cc2
=> fix #21 Ensure palette frames are RGBA

streamdeck_ui/display/display_grid.py
each button contains a pipeline that need to be initialized correctly, that was not correctly initialized when a new page was added resulting in weird behavior where the icons of the previous page are visualized when the button in the selected page does not have any property set
=> fix: ensure correctly initialization of pipeline when new page is added

streamdeck_ui/gui.py
when a button include actions like switch page or switch button may happen that the destination include a switch and results in calling the two switch when only one should be called
fixed by pull all the data first then do the switches
if you want to confirm this bug before actually merging this
- in the development
- in some page (example: page 1) to some button (button 10) set switch page (set to switch to page 2)
- in the page 2 to the button 10, add at last two states and make the state 1 switch to state 2 and state2  switch to state 1
- ensure each state has a different color or label so you will notice
- go to page 1 and hit the button 10, the page will switch but also the button will change its state
The correct behavior is: when hit button 10 in page 1 should switch to page 2, …
=> fix: switch page/button state race condition

streamdeck_ui/display/image_filter.py
Pillow support image with multiple modes
Due to how pipeline works when an imagen with transparency is being used a transparency mask need to be pass, but the application was doing that only for RGBA mode frames
Converting every frame to RGBA is expensive, so we convert frames of supported modes that we know that may contain transparency
Useful link: https://pillow.readthedocs.io/en/stable/handbook/concepts.html and many of them supports transparency
=> Fix  images with  transparency

scripts/lint.sh, streamdeck_ui/display/image_filter.py, streamdeck_ui/gui.py
This PR addresses issue #126. Pillow is bumped to pass safety check (everything appears to be working still...). Added set -x to lint.sh to make it easier to follow which command generated which output.
=> fix: allow button image to update with same selected file path

.github/workflows/test.yaml, poetry.lock, pyproject.toml, streamdeck_ui/gui.py
Bumping dependencies to address the failing Fedora builds #137 and add basic initial support for the stream deck plus
=> build: bump dependencies -- python 3.12, streamdeck 0.9.5

udev/60-streamdeck.rules
This was missing an entry for the Stream Deck Plus and was giving permission errors until I added it. The device has id 0084.
=> Update 60-streamdeck.rules for the Stream Deck Plus

streamdeck_ui/gui.py
The first argument passed to the `clicked` callback returns whether the item is `checked` or not.
This should resolve the issue reported in #197 and #200.
=> fix: resolve inability to select buttons in the ui

streamdeck_ui/display/display_grid.py, streamdeck_ui/display/image_filter.py
- The change to streamdeck_ui/display/image_filter.py scales images up as well as down. PIL's Image.thumbnail method can never return an image larger than the original image, which makes images smaller than the key size such as desktop icons - e.g. with a lower resolution like 32x32 or 48x48 - not fill up the entire key image space. Image.resize lets any icon fill up the key.
- The change to streamdeck_ui/display/display_grid.py is more subtle:
If you have more than one Stream Deck connected and they have different key image sizes - for example a Stream Deck XL with 96x96 keys and a Stream Deck Plus with 120x120 keys - two DisplayGrid instances are created. The first one initialize the static class-level EmptyFilter instance upon creation and sets its image size once. Then the second one …
=> Key image size bug fixes

streamdeck_ui/semaphore.py
First pull request ever, please have patience with me. From the original project there was a bug about leaving the semaphore lock file in the /tmp folder once the app terminates.
I believe this should fix that from happening by requesting the lock-file to be removed upon termination of the Semaphore instance.
=> Remove semaphore file once app terminates

docs/installation/arch.md, docs/installation/centos.md, docs/installation/fedora.md, docs/installation/opensuse.md, docs/installation/ubuntu.md, udev/60-streamdeck.rules
1. Fixing issue #213 by adding the Streamdeck XL device id to [60-streamdeck.rules](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/udev/60-streamdeck.rules)
2. Updated the installation docs to also integrate [Streamdeck XL and Streamdeck Plus](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/4fb2c7cfd5ad432d16fca06aac888767ea818f8d)
=> Add udev rule for Streamdeck XL and update docs regarding udev rules
